spring.application.name=bff
server.port=${PORT:8081}

pet.service.url=${PET_SERVICE_URL:http://pet-service:3001}
location.service.url=${LOCATION_SERVICE_URL:http://geo-service:3002}
match.service.url=${MATCH_SERVICE_URL:http://match-service:3003}

logging.level.com.sanosysalvos=INFO
logging.level.org.springframework.web=INFO