spring.application.name=bff
server.port=${PORT:8081}

pet.service.url=${PET_SERVICE_URL:http://localhost:3001}
location.service.url=${LOCATION_SERVICE_URL:http://localhost:3002}
match.service.url=${MATCH_SERVICE_URL:http://localhost:3003}

eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://54.68.101.229:8761/eureka/}
eureka.instance.preferIpAddress=true

logging.level.com.sanosysalvos=INFO
logging.level.org.springframework.web=INFO